### ISSUE TITLE
Generar dos anclas para Equipo (Dentro de Filosofia)

### ISSUE THREAD

**Issue by VaneRothbergEgo** [AgenciaEgo/Delta#7]
Hola @ekersten necesitaría si me podes crear dos anclas para que desde el cta de insitucionales directamente se muestre dentro de filosofia la parte donde se mencionan los miembros del equipo:

http://delta.egoagencydev.com/es/filosofia#equipo
http://delta.egoagencydev.com/en/philosophy#team

Podemos plis?

Gracias!

**Comment by ekersten** [comment]
hecho
